---
title: "Problema 9.1"
author: "Equipo 3"
date: "26/2/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(knitr)
library(tinytex)
library(ggplot2)
options(knitr.duplicate.label = "allow")
```

## Ejercicio 9.1
Considere una firma que genera un producto utilizando una combinación de capital y trabajo tipo Cobb-Douglas: $Y=K^\alpha L^{1-\alpha}$ donde $0<\alpha<1$. Suponga que el precio de la firma es fijo en el corto plazo; así que toma como dados tanto el precio de su producto, $P$, como la cantidad producida $Y$. El mercado de insumos es competitivo; así que la firma toma los salrios $W$, y la renta del precio del capital $r_K$, como dados.

\begin{description}
\item[(a)] ¿Cual es la elección de la firma de $L$ dado $P$, $Y$, $W$, y $K$?
\item[(b)] Dada la elección de $L$, ¿Cual es el beneficio de la firma como una función de $P$, $Y$, $W$, y $K$?
\item[(c)] Encontrar las condiciones de primer orden para la maximización del beneficio siendo $K$ la variable de elección. ¿Se satisface la condición de segundo orden?
\item[(d)] Resolver la condición de primer orden para la elección de $K$ que maximiza el beneficio como una función de $P$, $Y$, $W$, y $r_K$. ¿Como afectan cada una de estas variables la elección de $K$?


\end{description}


### Solución.



### Inciso a)

 Dado $K$ y una cantidad fija de demanda ,$Y$, la firma contratara suficiente trabajo para satisfacer la demanda.
 Dada la función de producción.
$$                 Y=K^ \alpha L^{(1-\alpha)}
                                                            $$
 Entonces la firma contratara.
$$
                            L=Y^{\frac{1}{1-\alpha}}K^{\frac{-\alpha}{1-\alpha}}
                                                                                $$



### Inciso b)

 Sustituimos la expresión anterior correspondiente a la elección de trabajo de la firma en la función de beneficio, $\pi=PY-WL-r_KK$, entonces obtenemos:
$$ 
                \pi=PY-WY^{\frac{1}{1-\alpha}}K^{\frac{-\alpha}{1-\alpha}}-r_KK
                                                                               $$



### Inciso c)

 La condición de primer orden de la firma respecto la elección de $K$ es:
$$
\frac{\partial\pi}{\partial K}=\frac{\alpha}{1-\alpha}WY^{\frac{1}{1-\alpha}}K^{\frac{-\alpha}{1-\alpha}-1}-r_K=0
$$
 simplificando obtenemos:
$$
    \frac{\alpha}{1-\alpha}WY^{\frac{1}{1-\alpha}}K^{\frac{-1}{1-\alpha}}=r_K     
$$
 Dado que estamos maximizando requerimos que $\frac{\partial^2 \pi}{\partial K^2}<0$
$$
  \frac{\partial^2 \pi}{\partial K^2}=\frac{-1}{1-\alpha}\frac{\alpha}{1-\alpha}WY^{\frac{1}{1-\alpha}}K^{\frac{\alpha-2}{1-\alpha}}<0 
  $$
 La condición de segundo orden se satisface ya que $\alpha <1$.



### Inciso d)

 Despejando $K$ de la condición de primer orden obtenemos:
$$
              K^{\frac{1}{1-\alpha}}=\frac{\alpha}{1-\alpha}\frac{WY^{\frac{1}{1-\alpha}}}{r_K}
$$
 Elevando a $1-\alpha$ de ambos lados de la ecuación obtenemos la elección de $K$ de la firma:
$$
               K=Y\left(\frac{\alpha}{1-\alpha}\right)^{1-\alpha}\left(\frac{W}{r_K}\right)^{1-\alpha}
               $$
 La expresión anterior nos indica que los cambios en el precio del producto de la firma no afecta directamente la elección de $K$.
Para deducir el efecto que tienen el resto de las variables en la elección de $K$ calculamos las elasticidades con respecto cada una de las variables.
$$
                 \epsilon_W= W\frac{\partial ln K}{\partial W}= 1-\alpha>0
                 $$
 Esta expresión nos indica que aumentos en el salario elevan la demanda de $K$ de la firma.
$$
                \epsilon_{r_K}= r_K \frac{\partial ln r_K}{\partial r_K}= -(1-\alpha)<0
                $$
 La ecuación anterior implica que aumentos en el costo del capital reducen la demanda del mismo.
$$
         \epsilon_Y= Y \frac{\partial ln Y}{\partial Y}=1
         $$
 Esta ultima ecuación nos dice que aumentos en la producción elevan la elección optima de capital en la misma proporción.






















































